language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
notifications:
  email:
  - Benjamin.Eckardt@gmx.net
script: npm test
after_success:
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha test/**/*.test.js
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls --verbose
